# Dockerfile for flaskapp

FROM python:3.9-slim-buster

# Set working directory
WORKDIR /app


COPY . /app

# Install dependencies
RUN apt-get update && \
    pip3 install -r requirements.txt

# Expose necessary ports
EXPOSE 5000


CMD ["python", "app.py"]