# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Gemstoneprice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://gemstoneprices.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b01229ceb4894426bcf4a7e52dd601f1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_de0484e2084749519246062df767f676 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: gemstoneprices.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b01229ceb4894426bcf4a7e52dd601f1 }}/gemstone2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Gemstoneprice'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_57c02b7d76f04c8ca07c73639ff5e135 }}
        images: 'gemstoneprices.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b01229ceb4894426bcf4a7e52dd601f1 }}/gemstone2:${{ github.sha }}'